"""
100 hand-crafted logical reasoning & problem solving puzzles.
Difficulty: 1-20 easy, 21-50 medium, 51-80 hard, 81-100 expert.
Categories: pattern, sequence, math, riddle, deduction, spatial, logic_grid, lateral
"""

PUZZLES = [
    # ---------- EASY 1-20 ----------
    {"level": 1, "category": "sequence", "difficulty": "easy", "question": "What comes next in the series?  2, 4, 6, 8, __", "options": ["9", "10", "11", "12"], "answer": "10", "concept": "Arithmetic progression (add 2)"},
    {"level": 2, "category": "pattern", "difficulty": "easy", "question": "Which shape completes the pattern?  🔺 🔵 🔺 🔵 🔺 __", "options": ["🔺", "🔵", "🟨", "⬛"], "answer": "🔵", "concept": "Alternating pattern"},
    {"level": 3, "category": "math", "difficulty": "easy", "question": "If 3 apples cost $6, how much do 5 apples cost?", "options": ["$8", "$9", "$10", "$12"], "answer": "$10", "concept": "Unit rate"},
    {"level": 4, "category": "sequence", "difficulty": "easy", "question": "Find the missing number:  1, 3, 5, 7, __, 11", "options": ["8", "9", "10", "12"], "answer": "9", "concept": "Odd numbers"},
    {"level": 5, "category": "riddle", "difficulty": "easy", "question": "I have hands but cannot clap. What am I?", "options": ["A statue", "A clock", "A tree", "A robot"], "answer": "A clock", "concept": "Lateral thinking"},
    {"level": 6, "category": "math", "difficulty": "easy", "question": "What is half of a quarter?", "options": ["1/2", "1/4", "1/6", "1/8"], "answer": "1/8", "concept": "Fractions"},
    {"level": 7, "category": "deduction", "difficulty": "easy", "question": "All cats are mammals. Whiskers is a cat. Therefore, Whiskers is a...", "options": ["Dog", "Mammal", "Bird", "Fish"], "answer": "Mammal", "concept": "Syllogism"},
    {"level": 8, "category": "sequence", "difficulty": "easy", "question": "What comes next?  1, 4, 9, 16, __", "options": ["20", "24", "25", "30"], "answer": "25", "concept": "Perfect squares"},
    {"level": 9, "category": "spatial", "difficulty": "easy", "question": "How many sides does a hexagon have?", "options": ["4", "5", "6", "8"], "answer": "6", "concept": "Geometry"},
    {"level": 10, "category": "riddle", "difficulty": "easy", "question": "What has a neck but no head?", "options": ["A snake", "A shirt", "A bottle", "A guitar"], "answer": "A bottle", "concept": "Wordplay"},
    {"level": 11, "category": "pattern", "difficulty": "easy", "question": "A, C, E, G, __", "options": ["H", "I", "J", "K"], "answer": "I", "concept": "Skip a letter"},
    {"level": 12, "category": "math", "difficulty": "easy", "question": "If today is Wednesday, what day will it be 10 days later?", "options": ["Friday", "Saturday", "Sunday", "Monday"], "answer": "Saturday", "concept": "Modular arithmetic"},
    {"level": 13, "category": "sequence", "difficulty": "easy", "question": "Continue: 100, 90, 80, __, 60", "options": ["65", "70", "75", "85"], "answer": "70", "concept": "Countdown by 10"},
    {"level": 14, "category": "riddle", "difficulty": "easy", "question": "The more you take, the more you leave behind. What are they?", "options": ["Footsteps", "Photos", "Memories", "Words"], "answer": "Footsteps", "concept": "Metaphor"},
    {"level": 15, "category": "deduction", "difficulty": "easy", "question": "Anna is taller than Ben. Ben is taller than Carl. Who is shortest?", "options": ["Anna", "Ben", "Carl", "Cannot tell"], "answer": "Carl", "concept": "Transitive ordering"},
    {"level": 16, "category": "math", "difficulty": "easy", "question": "A rectangle has length 8 and width 3. What is its area?", "options": ["11", "22", "24", "32"], "answer": "24", "concept": "Area = L × W"},
    {"level": 17, "category": "pattern", "difficulty": "easy", "question": "Odd one out:  Dog, Cat, Cow, Car", "options": ["Dog", "Cat", "Cow", "Car"], "answer": "Car", "concept": "Category classification"},
    {"level": 18, "category": "sequence", "difficulty": "easy", "question": "3, 6, 12, 24, __", "options": ["36", "42", "48", "50"], "answer": "48", "concept": "Doubling"},
    {"level": 19, "category": "spatial", "difficulty": "easy", "question": "If you fold a square paper in half twice, how many rectangles do you get when unfolded?", "options": ["2", "3", "4", "6"], "answer": "4", "concept": "Paper folding"},
    {"level": 20, "category": "riddle", "difficulty": "easy", "question": "What gets wetter as it dries?", "options": ["Rain", "A sponge", "A towel", "Soap"], "answer": "A towel", "concept": "Paradox riddle"},

    # ---------- MEDIUM 21-50 ----------
    {"level": 21, "category": "sequence", "difficulty": "medium", "question": "Find the next number:  1, 1, 2, 3, 5, 8, __", "options": ["11", "13", "12", "15"], "answer": "13", "concept": "Fibonacci sequence"},
    {"level": 22, "category": "math", "difficulty": "medium", "question": "If 5 machines take 5 minutes to make 5 widgets, how long for 100 machines to make 100 widgets?", "options": ["5 min", "20 min", "100 min", "1 min"], "answer": "5 min", "concept": "Rate parallelism"},
    {"level": 23, "category": "deduction", "difficulty": "medium", "question": "Some flowers are red. All roses are flowers. Therefore, some roses are red.", "options": ["Definitely true", "Definitely false", "Cannot be determined", "Sometimes true"], "answer": "Cannot be determined", "concept": "Invalid syllogism"},
    {"level": 24, "category": "pattern", "difficulty": "medium", "question": "Which number is next?  2, 6, 12, 20, 30, __", "options": ["36", "40", "42", "44"], "answer": "42", "concept": "n(n+1)"},
    {"level": 25, "category": "riddle", "difficulty": "medium", "question": "I speak without a mouth and hear without ears. I have no body, but I come alive with wind. What am I?", "options": ["A shadow", "An echo", "A ghost", "A whisper"], "answer": "An echo", "concept": "Metaphorical riddle"},
    {"level": 26, "category": "math", "difficulty": "medium", "question": "A bat and a ball cost $1.10. The bat costs $1 more than the ball. How much does the ball cost?", "options": ["$0.10", "$0.05", "$0.15", "$0.20"], "answer": "$0.05", "concept": "Cognitive reflection"},
    {"level": 27, "category": "sequence", "difficulty": "medium", "question": "1, 4, 9, 16, 25, __, 49", "options": ["30", "36", "42", "48"], "answer": "36", "concept": "Squares"},
    {"level": 28, "category": "deduction", "difficulty": "medium", "question": "Three friends: Amy, Bob, Cara. Amy is not the tallest. Cara is shorter than Bob. Who is tallest?", "options": ["Amy", "Bob", "Cara", "Tie"], "answer": "Bob", "concept": "Constraint reasoning"},
    {"level": 29, "category": "pattern", "difficulty": "medium", "question": "AZ, BY, CX, DW, __", "options": ["EV", "EU", "FV", "EW"], "answer": "EV", "concept": "Mirror alphabet"},
    {"level": 30, "category": "spatial", "difficulty": "medium", "question": "A cube has how many edges?", "options": ["6", "8", "12", "16"], "answer": "12", "concept": "3D geometry"},
    {"level": 31, "category": "math", "difficulty": "medium", "question": "If it takes 8 painters 6 hours to paint a wall, how long for 4 painters?", "options": ["3 h", "6 h", "8 h", "12 h"], "answer": "12 h", "concept": "Inverse proportion"},
    {"level": 32, "category": "riddle", "difficulty": "medium", "question": "What can travel around the world while staying in a corner?", "options": ["A photo", "A stamp", "A phone", "A dream"], "answer": "A stamp", "concept": "Lateral thinking"},
    {"level": 33, "category": "sequence", "difficulty": "medium", "question": "2, 3, 5, 7, 11, __", "options": ["12", "13", "14", "15"], "answer": "13", "concept": "Prime numbers"},
    {"level": 34, "category": "deduction", "difficulty": "medium", "question": "A dog is either black or brown. If it's not brown, then it must be...", "options": ["White", "Grey", "Black", "Any color"], "answer": "Black", "concept": "Disjunctive syllogism"},
    {"level": 35, "category": "pattern", "difficulty": "medium", "question": "Odd one out:  Triangle, Square, Circle, Pentagon", "options": ["Triangle", "Square", "Circle", "Pentagon"], "answer": "Circle", "concept": "Polygons vs curves"},
    {"level": 36, "category": "math", "difficulty": "medium", "question": "The sum of two numbers is 20 and their difference is 4. What is the larger number?", "options": ["8", "10", "12", "14"], "answer": "12", "concept": "Simultaneous equations"},
    {"level": 37, "category": "logic_grid", "difficulty": "medium", "question": "John, Mary, and Sue own a cat, dog, and bird. John doesn't own the cat. Mary owns the dog. What does Sue own?", "options": ["Cat", "Dog", "Bird", "None"], "answer": "Cat", "concept": "Elimination logic"},
    {"level": 38, "category": "riddle", "difficulty": "medium", "question": "Forward I'm heavy, but backward I'm not. What am I?", "options": ["Weight", "Ton", "Load", "Iron"], "answer": "Ton", "concept": "Palindrome wordplay (ton→not)"},
    {"level": 39, "category": "sequence", "difficulty": "medium", "question": "1, 2, 4, 7, 11, 16, __", "options": ["20", "21", "22", "24"], "answer": "22", "concept": "Increment increases by 1"},
    {"level": 40, "category": "spatial", "difficulty": "medium", "question": "A clock shows 3:15. What is the angle between the hour and minute hands?", "options": ["0°", "7.5°", "15°", "22.5°"], "answer": "7.5°", "concept": "Clock hands geometry"},
    {"level": 41, "category": "math", "difficulty": "medium", "question": "What is 15% of 200?", "options": ["20", "25", "30", "35"], "answer": "30", "concept": "Percentages"},
    {"level": 42, "category": "pattern", "difficulty": "medium", "question": "J F M A M J J A S O N __", "options": ["D", "N", "J", "F"], "answer": "D", "concept": "Months initials"},
    {"level": 43, "category": "deduction", "difficulty": "medium", "question": "If it rains, the ground gets wet. The ground is wet. Can we conclude it rained?", "options": ["Yes, always", "No, other causes possible", "Only in summer", "Only if forecast said so"], "answer": "No, other causes possible", "concept": "Affirming the consequent"},
    {"level": 44, "category": "sequence", "difficulty": "medium", "question": "0, 1, 1, 2, 3, 5, 8, 13, __", "options": ["18", "20", "21", "24"], "answer": "21", "concept": "Fibonacci"},
    {"level": 45, "category": "riddle", "difficulty": "medium", "question": "The more of me you take, the more you leave behind. I am...", "options": ["Time", "Steps", "Water", "Air"], "answer": "Steps", "concept": "Wordplay"},
    {"level": 46, "category": "math", "difficulty": "medium", "question": "A train 100m long crosses a pole in 5 seconds. Its speed is?", "options": ["10 m/s", "20 m/s", "50 m/s", "5 m/s"], "answer": "20 m/s", "concept": "Speed = distance/time"},
    {"level": 47, "category": "logic_grid", "difficulty": "medium", "question": "Alex, Beth, Carl live in floors 1, 2, 3 (not in order). Alex isn't on 1. Carl is above Beth. Who is on floor 2?", "options": ["Alex", "Beth", "Carl", "Anyone"], "answer": "Alex", "concept": "Positional deduction"},
    {"level": 48, "category": "pattern", "difficulty": "medium", "question": "Which is the odd one?  144, 121, 100, 84, 64", "options": ["144", "100", "84", "64"], "answer": "84", "concept": "Perfect squares (84 isn't)"},
    {"level": 49, "category": "spatial", "difficulty": "medium", "question": "How many faces does a triangular prism have?", "options": ["3", "4", "5", "6"], "answer": "5", "concept": "3D shapes"},
    {"level": 50, "category": "math", "difficulty": "medium", "question": "If 2x + 3 = 11, what is x?", "options": ["3", "4", "5", "6"], "answer": "4", "concept": "Linear equation"},

    # ---------- HARD 51-80 ----------
    {"level": 51, "category": "sequence", "difficulty": "hard", "question": "1, 11, 21, 1211, 111221, __", "options": ["1112221", "312211", "1221111", "112211"], "answer": "312211", "concept": "Look-and-say sequence"},
    {"level": 52, "category": "riddle", "difficulty": "hard", "question": "You have 3 boxes: one has apples, one has oranges, one has both. All 3 are labeled wrong. You may pick 1 fruit from 1 box. How many picks to label all correctly?", "options": ["1", "2", "3", "Impossible"], "answer": "1", "concept": "Classic labeling puzzle"},
    {"level": 53, "category": "math", "difficulty": "hard", "question": "In a race, you overtake the person in 2nd place. What position are you in now?", "options": ["1st", "2nd", "3rd", "Cannot say"], "answer": "2nd", "concept": "Common intuition trap"},
    {"level": 54, "category": "logic_grid", "difficulty": "hard", "question": "Four cards show A, K, 5, 8. Rule: 'If vowel on one side, even on other.' Which cards to flip to test?", "options": ["A only", "A & 5", "A & 8", "A, K, 5, 8"], "answer": "A & 5", "concept": "Wason selection task"},
    {"level": 55, "category": "deduction", "difficulty": "hard", "question": "You are in a room with 2 doors. One leads to freedom, one to death. Two guards: one always lies, one always tells the truth. One question. What to ask?", "options": ["Are you the liar?", "Which door is safe?", "What would the other guard say is the safe door?", "Do you tell the truth?"], "answer": "What would the other guard say is the safe door?", "concept": "Two-guards puzzle"},
    {"level": 56, "category": "math", "difficulty": "hard", "question": "How many zeros are at the end of 25!?", "options": ["4", "5", "6", "7"], "answer": "6", "concept": "Factorial trailing zeros"},
    {"level": 57, "category": "sequence", "difficulty": "hard", "question": "1, 2, 6, 24, 120, __", "options": ["360", "600", "720", "840"], "answer": "720", "concept": "Factorials"},
    {"level": 58, "category": "spatial", "difficulty": "hard", "question": "A cube is painted, then cut into 27 small cubes. How many small cubes have exactly 2 painted faces?", "options": ["6", "8", "12", "20"], "answer": "12", "concept": "Painted cube edges"},
    {"level": 59, "category": "riddle", "difficulty": "hard", "question": "A man leaves home, turns left three times, and returns home to find two masked men waiting. Who are they?", "options": ["Thieves", "The catcher and umpire", "Ghosts", "Police"], "answer": "The catcher and umpire", "concept": "Baseball riddle"},
    {"level": 60, "category": "math", "difficulty": "hard", "question": "If you have a 3L jug and a 5L jug, how do you measure exactly 4 liters?", "options": ["Fill 5L, pour into 3L, remaining is 2L, dump 3L, pour 2L in, refill 5L, top up 3L, remainder is 4L", "Impossible", "Fill 3L twice", "Fill 5L and dump 1L"], "answer": "Fill 5L, pour into 3L, remaining is 2L, dump 3L, pour 2L in, refill 5L, top up 3L, remainder is 4L", "concept": "Water jug puzzle"},
    {"level": 61, "category": "deduction", "difficulty": "hard", "question": "3 hats are placed on 3 people who can see the others' hats. 2 red, 1 blue. Each is asked what color theirs is. First two say 'don't know'. What does the third say?", "options": ["Red", "Blue", "Don't know", "Depends"], "answer": "Red", "concept": "Common knowledge deduction"},
    {"level": 62, "category": "pattern", "difficulty": "hard", "question": "What comes next?  O T T F F S S E __", "options": ["N", "T", "E", "S"], "answer": "N", "concept": "One, Two, Three... initials"},
    {"level": 63, "category": "logic_grid", "difficulty": "hard", "question": "Alice, Bob, Cathy, Dan. Ages 10, 12, 14, 16. Alice is younger than Bob. Cathy is older than Dan. Dan is older than Bob. Youngest?", "options": ["Alice", "Bob", "Cathy", "Dan"], "answer": "Alice", "concept": "Multi-constraint ordering"},
    {"level": 64, "category": "math", "difficulty": "hard", "question": "A snail climbs a 10m wall. Climbs 3m each day, slips back 2m each night. On which day does it reach the top?", "options": ["7", "8", "9", "10"], "answer": "8", "concept": "Snail climbing puzzle"},
    {"level": 65, "category": "sequence", "difficulty": "hard", "question": "1, 3, 6, 10, 15, __", "options": ["18", "20", "21", "24"], "answer": "21", "concept": "Triangular numbers"},
    {"level": 66, "category": "riddle", "difficulty": "hard", "question": "You're in a dark room with a candle, an oil lamp, and a fireplace. You have only one match. What do you light first?", "options": ["Candle", "Oil lamp", "Fireplace", "The match"], "answer": "The match", "concept": "Trick question"},
    {"level": 67, "category": "spatial", "difficulty": "hard", "question": "How many small triangles are in a big triangle divided into 3 rows?", "options": ["6", "7", "9", "13"], "answer": "13", "concept": "Sierpinski counting"},
    {"level": 68, "category": "deduction", "difficulty": "hard", "question": "5 pirates split 100 gold. Most senior proposes; if <50% agree (including self), he dies. Repeat. What does the top pirate propose (assuming logical greedy pirates)?", "options": ["20 each", "98,0,1,0,1", "50,25,25,0,0", "100,0,0,0,0"], "answer": "98,0,1,0,1", "concept": "Pirate game theory"},
    {"level": 69, "category": "math", "difficulty": "hard", "question": "Find the sum of first 100 natural numbers.", "options": ["4950", "5000", "5050", "5100"], "answer": "5050", "concept": "Gauss formula n(n+1)/2"},
    {"level": 70, "category": "pattern", "difficulty": "hard", "question": "8, 5, 4, 9, 1, 7, 6, 10, 3, 2 — what's the pattern?", "options": ["Reverse counting", "Alphabetical order of number names", "Random", "Primes first"], "answer": "Alphabetical order of number names", "concept": "Alpha order: eight, five, four, nine..."},
    {"level": 71, "category": "logic_grid", "difficulty": "hard", "question": "5 houses, 5 colors, 5 nationalities. Norwegian is in 1st house. Who lives next to blue house? (Simplified Einstein puzzle) Blue is 2nd house.", "options": ["Norwegian", "Danish", "German", "Cannot say"], "answer": "Norwegian", "concept": "Adjacency in constraint puzzle"},
    {"level": 72, "category": "riddle", "difficulty": "hard", "question": "A father and son crash. Father dies. Son taken to hospital. Surgeon says 'I can't operate — that's my son.' How?", "options": ["Stepfather", "The surgeon is his mother", "Adopted", "Ghost"], "answer": "The surgeon is his mother", "concept": "Bias-check riddle"},
    {"level": 73, "category": "math", "difficulty": "hard", "question": "What is the probability of rolling a sum of 7 with two dice?", "options": ["1/6", "1/8", "1/12", "1/36"], "answer": "1/6", "concept": "Dice probability"},
    {"level": 74, "category": "sequence", "difficulty": "hard", "question": "2, 12, 36, 80, 150, __", "options": ["210", "252", "300", "336"], "answer": "252", "concept": "n²(n+1)"},
    {"level": 75, "category": "spatial", "difficulty": "hard", "question": "Fold a 6x6 grid along the diagonal. How many unique squares overlap?", "options": ["15", "18", "21", "36"], "answer": "21", "concept": "Symmetric folding"},
    {"level": 76, "category": "deduction", "difficulty": "hard", "question": "There are 100 lockers, all closed. 100 students. Student n toggles every nth locker. How many are open at the end?", "options": ["10", "25", "50", "100"], "answer": "10", "concept": "Perfect squares — only 1,4,9,16,25,36,49,64,81,100"},
    {"level": 77, "category": "math", "difficulty": "hard", "question": "A rope burns unevenly in 60 minutes. Using 2 ropes, measure exactly 45 min.", "options": ["Burn 1 from both ends, other from one end. After 1st done (30m), light other end of 2nd. It burns in 15 more.", "Impossible", "Burn both at once", "Cut each into halves"], "answer": "Burn 1 from both ends, other from one end. After 1st done (30m), light other end of 2nd. It burns in 15 more.", "concept": "Rope burning puzzle"},
    {"level": 78, "category": "logic_grid", "difficulty": "hard", "question": "Truth-tellers always say truth, liars always lie. You meet 3 people: A says 'B is a liar'. B says 'C is a truth-teller'. C says 'A and B are the same type'. What is C?", "options": ["Liar", "Truth-teller", "Cannot determine", "Both"], "answer": "Liar", "concept": "Knights and knaves"},
    {"level": 79, "category": "pattern", "difficulty": "hard", "question": "Odd one out:  4, 9, 16, 25, 36, 48, 64", "options": ["4", "25", "48", "64"], "answer": "48", "concept": "48 is not a perfect square"},
    {"level": 80, "category": "riddle", "difficulty": "hard", "question": "You have 8 identical balls; one is heavier. With a balance scale, minimum weighings to find it?", "options": ["1", "2", "3", "4"], "answer": "2", "concept": "Divide into thirds"},

    # ---------- EXPERT 81-100 ----------
    {"level": 81, "category": "math", "difficulty": "expert", "question": "A monkey climbs a tree; each hour it climbs 3m and slips 1m. Tree is 20m. When does it reach the top?", "options": ["10th hour", "9th hour", "18th hour", "11th hour"], "answer": "9th hour", "concept": "Net gain vs final climb"},
    {"level": 82, "category": "logic_grid", "difficulty": "expert", "question": "5 people in a line, each wearing black or white hat. They can only see the ones in front. Starting from the back, they guess their hat color. Best strategy guarantees at least how many correct?", "options": ["3", "4", "5", "Cannot guarantee"], "answer": "4", "concept": "Parity signal — first sacrifices, next 4 guaranteed"},
    {"level": 83, "category": "deduction", "difficulty": "expert", "question": "A king says 'You'll be hanged, and I promise the day will be a total surprise.' Executioner comes some day M-F. Can this happen logically?", "options": ["Yes any day", "Only Friday", "Paradox — cannot be a surprise if logical", "Only Monday"], "answer": "Paradox — cannot be a surprise if logical", "concept": "Unexpected hanging paradox"},
    {"level": 84, "category": "math", "difficulty": "expert", "question": "How many ways can you arrange the letters in 'LEVEL'?", "options": ["30", "60", "120", "24"], "answer": "30", "concept": "Permutations with repetition: 5!/(2!2!)"},
    {"level": 85, "category": "sequence", "difficulty": "expert", "question": "1, 2, 720!, ... — which value equals ((3!)!)!/(3!)! ?", "options": ["6", "120", "720", "119!"], "answer": "119!", "concept": "Nested factorials"},
    {"level": 86, "category": "spatial", "difficulty": "expert", "question": "Möbius strip has how many sides?", "options": ["1", "2", "3", "0"], "answer": "1", "concept": "Topology"},
    {"level": 87, "category": "riddle", "difficulty": "expert", "question": "100 prisoners, 100 boxes with their names randomly. Each opens 50 boxes; all must find their own to survive. Best strategy success prob?", "options": ["~0", "1/100", "~31%", "~50%"], "answer": "~31%", "concept": "100 prisoners problem"},
    {"level": 88, "category": "math", "difficulty": "expert", "question": "Sum: 1 + 1/2 + 1/4 + 1/8 + ... = ?", "options": ["1", "1.5", "2", "Infinity"], "answer": "2", "concept": "Geometric series"},
    {"level": 89, "category": "logic_grid", "difficulty": "expert", "question": "10 coins, one fake (lighter). You have a balance scale but only 3 weighings. Can you find it?", "options": ["Yes", "No", "Only with 4", "Only if you know direction"], "answer": "Yes", "concept": "Ternary search: 3^3=27 ≥ 10"},
    {"level": 90, "category": "deduction", "difficulty": "expert", "question": "'This statement is false.' Is the statement true or false?", "options": ["True", "False", "Both", "Neither — paradox"], "answer": "Neither — paradox", "concept": "Liar paradox"},
    {"level": 91, "category": "pattern", "difficulty": "expert", "question": "Odd one out:  2, 3, 5, 7, 11, 13, 15, 17", "options": ["2", "11", "15", "17"], "answer": "15", "concept": "15 is composite"},
    {"level": 92, "category": "math", "difficulty": "expert", "question": "3 doors: 1 has a car, 2 have goats. You pick door 1. Host opens door 3 (goat). Should you switch?", "options": ["Yes, 2/3 chance", "No, 50/50", "No, 1/3 chance", "Doesn't matter"], "answer": "Yes, 2/3 chance", "concept": "Monty Hall problem"},
    {"level": 93, "category": "sequence", "difficulty": "expert", "question": "1, 11, 21, 1211, 111221, 312211, 13112221, __", "options": ["1113213211", "111312211", "11131221131211", "1113213221"], "answer": "1113213211", "concept": "Look-and-say continuation"},
    {"level": 94, "category": "spatial", "difficulty": "expert", "question": "How many diagonals does a decagon (10-gon) have?", "options": ["25", "30", "35", "45"], "answer": "35", "concept": "n(n-3)/2"},
    {"level": 95, "category": "riddle", "difficulty": "expert", "question": "Two trains 100 miles apart approach at 50 mph each. A fly at 75 mph zips back-and-forth between them until they collide. Total distance flown?", "options": ["50 mi", "75 mi", "100 mi", "150 mi"], "answer": "75 mi", "concept": "Time × speed shortcut"},
    {"level": 96, "category": "logic_grid", "difficulty": "expert", "question": "Blue-eyed islanders puzzle: 100 blue, 100 brown. All perfectly logical. Nobody knows their own eye color. A stranger says 'I see at least one blue eye.' When do blue-eyed leave?", "options": ["Never", "Day 1", "Day 50", "Day 100"], "answer": "Day 100", "concept": "Common knowledge induction"},
    {"level": 97, "category": "math", "difficulty": "expert", "question": "Golden ratio φ satisfies φ² = φ + 1. Approx value?", "options": ["1.414", "1.618", "1.732", "2.718"], "answer": "1.618", "concept": "Golden ratio"},
    {"level": 98, "category": "deduction", "difficulty": "expert", "question": "You have 12 balls, one is different weight (unknown heavier/lighter). Find it and its type in 3 weighings on balance?", "options": ["Possible", "Impossible", "Only if you know direction", "Only in 4 weighings"], "answer": "Possible", "concept": "12 balls classic puzzle"},
    {"level": 99, "category": "sequence", "difficulty": "expert", "question": "What comes next?  1, 2, 4, 8, 16, 31, __", "options": ["57", "62", "63", "64"], "answer": "57", "concept": "Circle-cut sequence (Moser's)"},
    {"level": 100, "category": "riddle", "difficulty": "expert", "question": "The Final Boss: A logician says 'I will lie to you.' If everything else they say is true, is this statement true or false?", "options": ["True", "False", "Both", "Neither — self-referential paradox"], "answer": "Neither — self-referential paradox", "concept": "Self-reference — you did it! 🧠👑"},
]

def get_all_puzzles_meta():
    return [{"level": p["level"], "category": p["category"], "difficulty": p["difficulty"]} for p in PUZZLES]

def get_puzzle(level: int):
    for p in PUZZLES:
        if p["level"] == level:
            return p
    return None
